kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: Ingress-Flask
  annotations:
    #This is for basically path trimming like if go on browser myntra/nike-shoes/size10..... it will redirect to myntra/nike-shoes
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # For integrating with cluster manager which we created
    cluster-manager.io/service-name: flask-service
    # For routing traffic to HTTPS 
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - host:
    - kkrishflask.duckdns.com
    secretName: kkrishflask-tls
  rules:
    - hosts: kkrishflask.duckdns.com
      http:
        - paths:
            pathType: Prefix
            backend:
              service:
                name: flask-service
                port: 
                  number:5000
      