kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: Ingress-Flask
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cluster-manager.io/service-name: flask-service
spec:
  ingressClassName: nginx
  tls:
  - host:
    - kkrishflask.duckdns.com
    secretName: kkrishflask-tls
  rules:
    - hosts: kkrishflask.duckdns.com
      http:
        - paths:
            pathType: Prefix
            backend:
              service:
                name: flask-service
                port: 
                  number:5000
      